import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { BsGithub } from "react-icons/bs";
import { IoEnterOutline } from "react-icons/io5";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-full flex-col items-center justify-center">
        <div className="fixed -z-10 h-screen w-screen overflow-hidden">
          <Image
            src={"/images/storm.jpg"}
            alt="clouds"
            style={{ objectFit: "cover", userSelect: "none" }}
            fill
            quality={100}
            sizes="100vw"
          />
        </div>
        <div className="absolute flex flex-col gap-4 p-4">
          <div className="flex flex-col text-center">
            <span className="text-home-title text-white">T3 Weather App</span>
            <span className="text-home-subtitle text-white">
              A simple weather app made with love.
            </span>
          </div>
          <div className="flex items-center justify-center gap-4 home-buttons-breakpoint:flex-col">
            <Link
              href={"https://www.google.cl"}
              className="inline-flex w-full justify-center gap-3 rounded bg-gray-300 p-2 text-center font-bold text-gray-800 hover:bg-gray-400"
            >
              <IoEnterOutline className="text-home-icons" />
              <span className="text-home-button">Sitio</span>
            </Link>
            <Link
              href={"https://www.youtube.com"}
              className="inline-flex w-full justify-center gap-3 rounded border-2 border-gray-300 bg-transparent p-2 text-center font-bold text-gray-800 hover:bg-white hover:bg-opacity-20"
            >
              <BsGithub className="text-home-icons text-white" />
              <span className="text-home-button text-white">Código</span>
            </Link>
          </div>
          <div className="flex"></div>
          <div className="flex"></div>
        </div>
      </main>
    </>
  );
};

export default Home;
