import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { BsGithub } from "react-icons/bs";
import { IoEnterOutline } from "react-icons/io5";
import HomeLinkButton from "../components/HomeLinkButton";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-full flex-col items-center justify-center">
        <div className="fixed -z-10 h-screen w-screen overflow-hidden">
          <Image
            src={"/images/storm.jpg"}
            alt="clouds"
            style={{ objectFit: "cover", userSelect: "none" }}
            fill
            quality={100}
            sizes="100vw"
          />
        </div>
        <div className="absolute flex flex-col gap-4 p-4">
          <div className="flex flex-col text-center">
            <span className="text-home-title text-white">T3 Weather App</span>
            <span className="text-home-subtitle text-white">
              A simple weather app made with love
            </span>
          </div>
          <div className="flex items-center justify-center gap-4 home-buttons-breakpoint:flex-col">
            <HomeLinkButton
              url="https://www.google.cl"
              linkStyle="inline-flex w-full justify-center items-center gap-3 rounded bg-gray-300 p-2 text-center font-bold text-gray-800 hover:bg-gray-400"
              IconElement={IoEnterOutline}
              buttonDescription="Entrar"
              whiteColor={false}
            />
            <HomeLinkButton
              url="https://www.youtube.com"
              linkStyle="inline-flex w-full justify-center items-center gap-3 rounded border-2 border-gray-300 bg-transparent p-2 text-center font-bold text-gray-800 hover:bg-white hover:bg-opacity-20"
              IconElement={BsGithub}
              buttonDescription="Código"
              whiteColor={true}
            />
          </div>
          <div className="flex"></div>
          <div className="flex"></div>
        </div>
      </main>
    </>
  );
};

export default Home;
